<?php

/**
 * @file
 * Primary module hooks for Hello World module.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 * 
 * Make the Promotion Options details component open by default in node creation forms.
 */
function hello_world_form_alter(&$form, FormStateInterface $form_state, $form_id) : void {
    if ($form_id == 'node_page_form') {
        // ksm($form);
        $form['options']['#open'] = TRUE;
    }
}